// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4SVlbbWZiFqwbOqsttuog5FeEQdP0OWI',
    appId: '1:933167332869:web:786f1715e5b344ec8ae66c',
    messagingSenderId: '933167332869',
    projectId: 'satubeacukai-fd692',
    authDomain: 'satubeacukai-fd692.firebaseapp.com',
    storageBucket: 'satubeacukai-fd692.appspot.com',
    measurementId: 'G-ZCV87FGMK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6HGVl_7_qYzVfVhUlpOSMzQKiWlQoqw4',
    appId: '1:933167332869:android:e465b3bddaad70098ae66c',
    messagingSenderId: '933167332869',
    projectId: 'satubeacukai-fd692',
    storageBucket: 'satubeacukai-fd692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-OqUD-X_17Q5w3Hgym0teAEO8JBTB8Kc',
    appId: '1:933167332869:ios:0749df27ac695de88ae66c',
    messagingSenderId: '933167332869',
    projectId: 'satubeacukai-fd692',
    storageBucket: 'satubeacukai-fd692.appspot.com',
    iosBundleId: 'com.example.satubeacukai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-OqUD-X_17Q5w3Hgym0teAEO8JBTB8Kc',
    appId: '1:933167332869:ios:0749df27ac695de88ae66c',
    messagingSenderId: '933167332869',
    projectId: 'satubeacukai-fd692',
    storageBucket: 'satubeacukai-fd692.appspot.com',
    iosBundleId: 'com.example.satubeacukai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4SVlbbWZiFqwbOqsttuog5FeEQdP0OWI',
    appId: '1:933167332869:web:c8d02434c0ae51b58ae66c',
    messagingSenderId: '933167332869',
    projectId: 'satubeacukai-fd692',
    authDomain: 'satubeacukai-fd692.firebaseapp.com',
    storageBucket: 'satubeacukai-fd692.appspot.com',
    measurementId: 'G-RFVDTQGLPW',
  );
}
